from django.urls import path
from .views import ComponentListView, ComponentDetailView, ComponentCreateView, ComponentUpdateView, ComponentDeleteView, Component   


urlpatterns = [
    path('components/', ComponentListView.as_view, name = 'component_list'),
    path ('components/<int:pk>/', ComponentDetailView.as_view(), name = 'component_detail'),
    path('create/', ComponentCreateView.as_view(), name='component_create'),
    path('<int:pk>/update/', ComponentUpdateView.as_view(), name='component_update'),
    path('<int:pk>/delete/', ComponentDeleteView.as_view(), name='component_delete'),
    # path('search/', ComponentSearchView.as_view(), name='component_search'),
    # path('filter/', ComponentFilterView.as_view(), name='component_filter'),
    # path('recommend/', ComponentRecommendationView.as_view(), name='component_recommend'),
    # path('sale/', ComponentSaleView.as_view(), name='component_sale'),
    # path('wishlist/', ComponentWishlistView.as_view(), name='component_wishlist'),
    # path('buildlist/', ComponentBuildListView.as_view(), name='component_build_list'),
    # path('build/', ComponentBuildView.as_view(), name='component_build'),
    # path('build/<int:pk>/', ComponentBuildDetailView.as_view(), name='component_build_detail'),
    # path('build/<int:pk>/update/', ComponentBuildUpdateView.as_view(), name='component_build_update'),
    # path('build/<int:pk>/delete/', ComponentBuildDeleteView.as_view(), name='component_build_delete'),
    # path('build/<int:pk>/add/', ComponentBuildAddView.as_view(), name='component_build_add'),
    # path('build/<int:pk>/remove/', ComponentBuildRemoveView.as_view(), name='component_build_remove'),
    # path('build/<int:pk>/recommend/', ComponentBuildRecommendationView.as_view(), name='component_build_recommend'),
    # path('build/<int:pk>/sale/', ComponentBuildSaleView.as_view(), name='component_build_sale'),
    # path('build/<int:pk>/wishlist/', ComponentBuildWishlistView.as_view(), name='component_build_wishlist'),
    # path('build/<int:pk>/compare/', ComponentBuildCompareView.as_view(), name='component_build_compare'),
    # path('build/<int:pk>/export/', ComponentBuildExportView.as_view(), name='component_build_export'),
    # path('build/<int:pk>/import/', ComponentBuildImportView.as_view(), name='component_build_import'),
    # path('build/<int:pk>/share/', ComponentBuildShareView.as_view(), name='component_build_share'),
    # path('build/<int:pk>/duplicate/', ComponentBuildDuplicateView.as_view(), name='component_build_duplicate'),
    # path('build/<int:pk>/publish/', ComponentBuildPublishView.as_view(), name='component_build_publish'),
    # path('build/<int:pk>/unpublish/', ComponentBuildUnpublishView.as_view(), name='component_build_unpublish'),
    # path('build/<int:pk>/like/', ComponentBuildLikeView.as_view(), name='component_build_like'),
    # path('build/<int:pk>/unlike/', ComponentBuildUnlikeView.as_view(), name='component_build_unlike'),
    # path('build/<int:pk>/comment/', ComponentBuildCommentView.as_view(), name='component_build_comment'),
    # path('build/<int:pk>/rate/', ComponentBuildRateView.as_view(), name='component_build_rate'),
    # path('build/<int:pk>/report/', ComponentBuildReportView.as_view(), name='component_build_report'),
    # path('build/<int:pk>/flag/', ComponentBuildFlagView.as_view(), name='component_build_flag'),
    # path('build/<int:pk>/subscribe/', ComponentBuildSubscribeView.as_view(), name='component_build_subscribe'),
    # path('build/<int:pk>/unsubscribe/', ComponentBuildUnsubscribeView.as_view(), name='component_build_unsubscribe'),
    # path('build/<int:pk>/download/', ComponentBuildDownloadView.as_view(), name='component_build_download'),
    # path('build/<int:pk>/upload/', ComponentBuildUploadView.as_view(), name='component_build_upload'),
    # path('build/<int:pk>/print/', ComponentBuildPrintView.as_view(), name='component_build_print'),
    # path('build/<int:pk>/preview/', ComponentBuildPreviewView.as_view(), name='component_build_preview'),
    # path('build/<int:pk>/embed/', ComponentBuildEmbedView.as_view(), name='component_build_embed'),
    # path('build/<int:pk>/export/pdf/', ComponentBuildExportPdfView.as_view(), name='component_build_export_pdf'),
    # path('build/<int:pk>/export/csv/', ComponentBuildExportCsvView.as_view(), name='component_build_export_csv'),
    # path('build/<int:pk>/export/xls/', ComponentBuildExportXlsView.as_view(), name='component_build_export_xls'),
    # path('build/<int:pk>/export/json/', ComponentBuildExportJsonView.as_view(), name='component_build_export_json'),
    # path('build/<int:pk>/export/xml/', ComponentBuildExportXmlView.as_view(), name='component_build_export_xml'),
    # path('build/<int:pk>/export/yaml/', ComponentBuildExportYamlView.as_view(), name='component_build_export_yaml'),
    # path('build/<int:pk>/export/txt/', ComponentBuildExportTxtView.as_view(), name='component_build_export_txt'),
    # path('build/<int:pk>/export/md/', ComponentBuildExportMdView.as_view(), name='component_build_export_md'),
    # path('build/<int:pk>/export/html/', ComponentBuildExportHtmlView.as_view(), name='component_build_export_html'),
    # path('build/<int:pk>/export/docx/', ComponentBuildExportDocxView.as_view(), name='component_build_export_docx'),
    # path('build/<int:pk>/export/odt/', ComponentBuildExportOdtView.as_view(), name='component_build_export_odt'),
]